nodes:
  - node: 1
    name: Mission
    type: control_flow
    subtype: sequence
    parent: 0
  - node: 2
    name: Take off
    type: execution
    subtype: task
    task: TAKE_OFF
    wait_for_completion: false
    parent: 1
  - node: 3
    name: Follow path
    type: execution
    subtype: task
    task: FOLLOW_PATH
    parameters: "path: [  [0, 0, 1] ,  [2, 0, 1] , [2, 2, 1],[0,0,1] ]"
    wait_for_completion: false
    parent: 1
  - node: 4
    name: Rotate
    type: execution
    subtype: task
    task: ROTATE
    parameters: "angle: 180"
    wait_for_completion: false
    parent: 1
  - node: 5
    name: Land
    type: execution
    subtype: task
    task: LAND
    wait_for_completion: false
    parent: 1

